Release process template
go-vela/community pull request #662
Opened 2022-08-22 19:09 UTC by chrispdriscoll

Create a template we can use for a repeatable release process

2022-09-16 19:50 UTC, plyr4 requested changes

2022-09-16 19:50 UTC, plyr4 commented on .github/ISSUE_TEMPLATE/Release Process.md
> +https://vela.dev.target.com/vela-canary/all-repo restart a build => results in all the other canary repos kicking off a build near the same time (a good way to watch them all is https://vela.dev.targ
we should remove the internal tgt references

2022-09-16 19:50 UTC, plyr4 commented on .github/ISSUE_TEMPLATE/Release Process.md
> +this cuts the go-vela external release https://pages.git.target.com/rapid/doc-site/13-vela/upgrades/#external (same link as for rc)
we should remove the internal tgt references

2022-09-16 19:50 UTC, plyr4 commented on .github/ISSUE_TEMPLATE/Release Process.md
> +keeping 1 story for the sake of this summary exercise; could be 1 where we link all bugs external bugs, or separate stories 1 per bug
some inconsistent paragraph capitalization, though not limited to this line

2022-09-16 19:50 UTC, plyr4 commented on .github/ISSUE_TEMPLATE/Release Process.md
> +## Release Story 7: add/modify / validate canary tests
canary testing is done via the internal installation, so maybe convert this step to 
"Validate Internal Installation" or something like that? a different company could run tests however they do?

2022-09-16 19:50 UTC, plyr4 commented on .github/ISSUE_TEMPLATE/Release Process.md
> +https://vela.prod.target.com/vela-canary/all-repo restart a build => results in all the other canary repos kicking off a build near the same time (a good way to watch them all is https://vela.prod.ta
internal references

2023-10-11 14:29 UTC, chrispdriscoll commented
We will review and update. Likely a full overhaul so we'll just close this.

2023-10-11 14:29 UTC, closed without merging