chore(release): release notes for v0.18
go-vela/community pull request #763
Opened 2023-03-03 19:28 UTC by ecrupper

Dependent on the release obviously, but also these docs PRs:

https://github.com/go-vela/docs/pull/349
https://github.com/go-vela/docs/pull/348

2023-03-03 19:59 UTC, wass3r requested changes

2023-03-03 19:59 UTC, wass3r commented on releases/v0.18.md
> +* When upgrading from `v0.18`, please take note of the [migration information](/migrations/v0.18/README.md)
```suggestion
* When upgrading from `v0.17`, please take note of the [migration information](/migrations/v0.18/README.md)
```

2023-03-03 21:44 UTC, wass3r approved these changes

2023-03-06 18:05 UTC, plyr4 approved these changes

2023-03-06 20:44 UTC, wass3r approved these changes

2023-03-06 20:45 UTC, merged